### ISSUE TITLE
Edit User Modal - Updates to resource attribute not saving

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/u-bahn-app#11]
**Steps to Reproduce**
1. Open Edit User Modal "TonyJ"
2. Edit `Location` field and set value = `USA`
3. Click Save
4. Click refresh in browser to ensure updates aren't saved only in cached app
5. Open TonyJ record
![image](https://user-images.githubusercontent.com/6014049/84283107-966c7600-ab08-11ea-8480-68f6b1985a72.png)

**Expected Result**
1. TonyJ user persists with Location = USA.
2. USA can be searched for and filtered on since USA has been added as a location on the user.

**Actual Result**
1. TonyJ user Location is null.
2. Unknown if USA location could be searched or filtered on after being added to the application since it did not persist on a user.

**Comment by callmekatootie** [comment]
Will be able to verify this once the Auth0 token issue is resolved - (See slack)

**Comment by callmekatootie** [comment]
@wdprice The issue that you faced was because the user that you attempted to edit did not have role, company and location attributes on them. Since these attributes did not exist, the UI did not know the attribute id of the field that it needs to update.

This has been documented in the assumptions here - https://github.com/topcoder-platform/u-bahn-app/issues/6#issuecomment-640056147

I have now updated the test data so that that user now has the attributes.

However, even then, I find that the updates are not going through - the UI is calling them correctly, but the issue lies with the bus api that we are using that posts the updates for the processor to update the data in elasticsearch.

@cwdcwd The bus api seems to have a validation on the topic name. I debugged to get this meaningful error (otherwise the error that it throws is really vague):

```
[
  {
    code: 'PATTERN',
    params: [ '^([a-zA-Z0-9]+\\.)+[a-zA-Z0-9]+$', 'u-bahn.action.update' ],
    message: 'String does not match pattern ^([a-zA-Z0-9]+\\.)+[a-zA-Z0-9]+$: u-bahn.action.update',
    path: [ 'topic' ],
    schemaId: undefined,
    description: 'Topic name should be a dot separated fully qualified name i.e. domain.type.operation.\n',
    [Symbol(z-schema/schema)]: {
      pattern: '^([a-zA-Z0-9]+\\.)+[a-zA-Z0-9]+$',
      description: 'Topic name should be a dot separated fully qualified name i.e. domain.type.operation.\n',
      example: 'notifications.action.email.project.topic.created',
      type: 'string',
      '__$validated': true
    },
    [Symbol(z-schema/json)]: {
      topic: 'u-bahn.action.update',
      originator: 'u-bahn-api',
      timestamp: '2020-05-27T07:03:21.678Z',
      'mime-type': 'application/json',
      payload: [Object]
    }
  }
]
```

Should the bus api be updated to accept the hyphen in the topic name or should we change the topics that we are using?

**Comment by callmekatootie** [comment]
This is now resolved.
