### ISSUE TITLE
Data is not uploaded when user uploads a correct CSV or XLS file

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#289]
https://take.ms/r7Ak0

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 03 (Upload)
3. Upload a valid file 
[BULK_UPLOAD_TEMPLATE_07_04.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908762/BULK_UPLOAD_TEMPLATE_07_04.zip)

**Actual Result:** Data is not uploaded when user uploads a correct CSV or XLS file

**Expected Result:** Should upload the data

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Checked the excel - the users that you were trying to create have the same email address and thus the process failed. Each user needs to have their own email address. Unfortunately, the only way to check the error is internally through logs and there's no feedback on the UI for now (intentional and not a bug).
