### ISSUE TITLE
[$20] No Debouncing for filters.

### ISSUE THREAD

**Issue by yogigachinmath** [topcoder-platform/u-bahn-app#403]
[BUG HUNT] To Reproduce follow the below steps or watch the video attached.
 
For the filters there is no debouncing period, which may overload the server and may cause main stack to 
overflow.
[issue3.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909287/issue3.zip)

**Comment by callmekatootie** [comment]
valid bug

**Comment by wdprice** [comment]
@callmekatootie Can you elaborate on what this issue is and the potential impact?

**Comment by callmekatootie** [comment]
@wdprice When the user starts typing and immediately after typing, we are currently sending the typed text to our api to fetch the suggestions - Debouce would require us to wait a few milliseconds, to wait for the user to finish typing, after which we send the text to the api to fetch the suggestions - thereby reducing the load (since it results in fewer api calls).

I estimate the effort to be around $20

**Comment by wdprice** [comment]
Understood. Proceed w/ fix.

**Comment by callmekatootie** [comment]
@nahidshahin Hang on - TCX did not create a contest for this ticket. Will check why - you will be the assignee - I may remove you but will add you back again

**Comment by callmekatootie** [comment]
@nahidshahin Closing this ticket - copied it over to https://github.com/topcoder-platform/u-bahn-app/issues/552.

Please use that.
