### ISSUE TITLE
[$20] UI issue on the Edit profile popup

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#99]
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to tab 01
3. Click Edit of a profile
4. Observe

**Actual Result:** UI issue on the Edit profile popup

**Expected Result:** Should display the layout properly

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/87247795-9b7c5800-c41b-11ea-8358-fe88ce440584.png)

**Comment by callmekatootie** [comment]
Valid bug

**Comment by callmekatootie** [comment]
Expected:

- In the Profile Edit modal, ensure that long group names are displayed properly. You have two options here - either provide ... ellipsis indicator and on hover show tooltip with full name, or do a word wrap (and for a really long word, break word) and in the case of the latter, provide proper padding
- If you do decide to show the whole name, then ensure that it pushes the content below it further below (such as the groups listing) instead of overlapping over it.

**Comment by callmekatootie** [comment]
No longer an issue since we have had individual tickets working on the long group name issues which have resolved it
